/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FilmsRouteImport } from './routes/films'
import { Route as DiscussionRouteImport } from './routes/discussion'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilmsCategorieRouteImport } from './routes/films.$categorie'
import { Route as FilmIdRouteImport } from './routes/film.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsRoute = FilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionRoute = DiscussionRouteImport.update({
  id: '/discussion',
  path: '/discussion',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsCategorieRoute = FilmsCategorieRouteImport.update({
  id: '/$categorie',
  path: '/$categorie',
  getParentRoute: () => FilmsRoute,
} as any)
const FilmIdRoute = FilmIdRouteImport.update({
  id: '/film/$id',
  path: '/film/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discussion': typeof DiscussionRoute
  '/messages': typeof MessagesRoute
  '/films': typeof FilmsRouteWithChildren
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/register': typeof RegisterRoute
  '/film/$id': typeof FilmIdRoute
  '/films/$categorie': typeof FilmsCategorieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discussion': typeof DiscussionRoute
  '/messages': typeof MessagesRoute
  '/films': typeof FilmsRouteWithChildren
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/register': typeof RegisterRoute
  '/film/$id': typeof FilmIdRoute
  '/films/$categorie': typeof FilmsCategorieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discussion': typeof DiscussionRoute
  '/messages': typeof MessagesRoute
  '/films': typeof FilmsRouteWithChildren
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/register': typeof RegisterRoute
  '/film/$id': typeof FilmIdRoute
  '/films/$categorie': typeof FilmsCategorieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discussion'
    | '/messages'
    | '/films'
    | '/login'
    | '/profil'
    | '/register'
    | '/film/$id'
    | '/films/$categorie'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discussion'
    | '/messages'
    | '/films'
    | '/login'
    | '/profil'
    | '/register'
    | '/film/$id'
    | '/films/$categorie'
  id:
    | '__root__'
    | '/'
    | '/discussion'
    | '/messages'
    | '/films'
    | '/login'
    | '/profil'
    | '/register'
    | '/film/$id'
    | '/films/$categorie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscussionRoute: typeof DiscussionRoute
  MessagesRoute: typeof MessagesRoute
  FilmsRoute: typeof FilmsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfilRoute: typeof ProfilRoute
  RegisterRoute: typeof RegisterRoute
  FilmIdRoute: typeof FilmIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films': {
      id: '/films'
      path: '/films'
      fullPath: '/films'
      preLoaderRoute: typeof FilmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussion': {
      id: '/discussion'
      path: '/discussion'
      fullPath: '/discussion'
      preLoaderRoute: typeof DiscussionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/$categorie': {
      id: '/films/$categorie'
      path: '/$categorie'
      fullPath: '/films/$categorie'
      preLoaderRoute: typeof FilmsCategorieRouteImport
      parentRoute: typeof FilmsRoute
    }
    '/film/$id': {
      id: '/film/$id'
      path: '/film/$id'
      fullPath: '/film/$id'
      preLoaderRoute: typeof FilmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FilmsRouteChildren {
  FilmsCategorieRoute: typeof FilmsCategorieRoute
}

const FilmsRouteChildren: FilmsRouteChildren = {
  FilmsCategorieRoute: FilmsCategorieRoute,
}

const FilmsRouteWithChildren = FilmsRoute._addFileChildren(FilmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscussionRoute: DiscussionRoute,
  MessagesRoute: MessagesRoute,
  FilmsRoute: FilmsRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfilRoute: ProfilRoute,
  RegisterRoute: RegisterRoute,
  FilmIdRoute: FilmIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
